# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
#  - name: Research
#     url: '#research'
#     weight: 20
  - name: Google Scholar
    url: 'https://scholar.google.com/citations?hl=en&user=E9jCXUcAAAAJ'
    weight: 30
  # - name: Teach
  #   url: 'teach'
  #   weight: 40